# -*- coding: utf-8 -*-
"""DL2A-lab-conv2D-2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o61ieyhjoDGkbKFy8hEdz5X8JXjc9ct6

This notebook is  a follow up of the lab session on Fashion MNIST. Be sure you did and understood the previous notebook on applying the feed-forward neural network with pytorch.

The goal is to incrementally build an image classifier based on convolutional layers. Since we consider images and convolution we will use Tensors with peculiar shapes in input. Moreover, this session is also the occasion to introduce "Max-pooling" and to sue "Batch-normalization" again.




# Dataset

First get the dataset. This is the same as last lab.
"""

# math, numpy and plot
import numpy as np
import math
import matplotlib
import matplotlib.pyplot as plt
# torch
import torch as th
import torch.autograd as autograd
import torch.nn.functional as F
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader

# gzip
import gzip
import pickle



# To download the file:
! wget -nc --no-check-certificate "https://drive.usercontent.google.com/download?id=1qx-a3KjzX2W66Aq84tnjGRUa10CTxOJN&confirm=t" -O "./fashion-mnist.pk.gz"

# Or if you prefer from Colab:
#import gdown
#url = 'https://drive.google.com/uc?id=1qx-a3KjzX2W66Aq84tnjGRUa10CTxOJN'
#output = 'fashion-mnist.pk.gz'
#gdown.download(url, output, quiet=False)
# Load the dataset
fp = gzip.open('./fashion-mnist.pk.gz','rb')
allXtrain, allYtrain, Xvalid, Yvalid, classlist  = pickle.load(fp)

"""##  Data format

The provided version is unfortunately not adapted to our purpose in terms of dimensions.
*Convolution2D* expects as input a Tensor with 4 dimensions $(N,C,H,W)$ with :

- N the batch dimension, *i.e* the number of images
- C the number of input channels, here it is 1
- H the height or number of rows of each image
- W the width  or number of columns of each image

## DataSet and DataLoader

In pytorch data handling is done in 2 steps:
- `DataSet`: a class to access the raw data, it can be tensors, files, distributed files, ...
- `DataLoader` (the class to iterate through the dataset and to get access to well prepared batch of data)

From the model viewpoint:
- During training and testing the model interacts with the `DataLoader` to go through the `DataSet`
- The Dataloader pick what is necessary in the `DataSet`  

Here we have Tensors, so we can use a `TensorDataSet`.  This abstraction for handling data is important. Depending on the application and the data types, it is very easier in practice to divide the process in two steps: the Dataset and the interaction between the model and the data via the dataset.
"""

BatchSize = 100
splittrain = 30000
# create your datset
# dataset = TensorDataset(x_tensor, y_tensor)
trainset = TensorDataset(allXtrain[:splittrain].view(splittrain,28,28)/255, allYtrain[:splittrain])
# create your dataloader
# if you have also labels you do
trainloader = DataLoader(trainset,batch_size=BatchSize, shuffle=True)
# Do the same for the validation set
validset = TensorDataset(allXtrain[splittrain:].view(splittrain,28,28)/255, allYtrain[splittrain:])
validloader = DataLoader(validset,batch_size=BatchSize, shuffle=True)

"""To look at one batch :"""

batch = next(iter(trainloader))
# Explore what you get as a batch
print(batch[0].shape)
print(batch[1].shape)

"""# Playing with convolution in 2D

Let start the exploration of convolution.The class we will use is called Conv2d. Read carefully the documentation of this module. Maybe you cannot understand everything. That's why it is useful to first play with the convolution with one image.
"""

# Extract one image to start and be sure you have the right dimensions.
image=batch[0][0]
print(image.shape)
plt.imshow(image.squeeze(),  matplotlib.pyplot.cm.gray)

"""Now create one convolution layer with 1 input channels, a kernel size of 3, and a stride of 1.
Try it and look at the output dimension.

"""

# TODO:
convol=nn.Conv2d(in_channels=1,out_channels=1,kernel_size =3)
res=convol(image.unsqueeze(0).unsqueeze(0))
print(image.unsqueeze(0).shape)
print(image.unsqueeze(0).unsqueeze(0).shape)
print(res.shape)

"""The resulting "image" is not of the same dimension, how to obtain an output with the same dimension (same question with a kernel size of 5) ?"""

# TODO
#need to put a padding
convol1=nn.Conv2d(in_channels=1,out_channels=1,kernel_size =3,padding=1)
res1=convol1(image.unsqueeze(0).unsqueeze(0))
print(res1.shape)

#froa kernel 5
convol2=nn.Conv2d(in_channels=1,out_channels=1,kernel_size =5,padding=2)
res2=convol2(image.unsqueeze(0).unsqueeze(0))
print(res2.shape)

"""We can define the parameters of the convolutional filter with our own hands. For that purpose we just have to create the Tensor we want and cast it in a *Parameter* object (usefull for autograd) and then assign it.
This is an example:
"""

# Create a convolutional filter
convFilter = nn.Conv2d(in_channels=1,out_channels=1,
                       kernel_size = 3, padding=1,
                       stride=1)
# build the weight matrix you want
W=th.ones(convFilter.weight.shape)
# Makes it a Parameter and assign
convFilter.weight = nn.Parameter(W)
im=image.unsqueeze(0).unsqueeze(0)

res = convFilter(im)
print(res.shape)
plt.subplot(1,2,1)
plt.imshow(im.squeeze(),  matplotlib.pyplot.cm.gray)
plt.subplot(1,2,2)
plt.imshow(F.relu(res).squeeze().detach(), matplotlib.pyplot.cm.gray)

print(W)

"""Now try to set the convolution fiter as follows:
$$
\left(
\begin{array}{ccc}
 -1 &2&-1\\
 -1 &2&-1\\
 -1 &2&-1
\end{array}
\right)
$$
and then as follows:
$$
\left(
\begin{array}{rrr}
 -1 &-1&-1\\
 2 &2&2\\
 -1 &-1&-1
\end{array}
\right)
$$
Try them on some images and visualize the results.
"""

# TODO



convFilter1 = nn.Conv2d(in_channels=1,out_channels=1,
                       kernel_size =3,padding=1)
W1=th.tensor([[-1,2,-1],[-1,2,-1],[-1,2,-1]],dtype=th.float32).unsqueeze(0).unsqueeze(0)
convFilter1.weight = nn.Parameter(W1)

convFilter2= nn.Conv2d(in_channels=1,out_channels=1,
                       kernel_size =3,padding=1)
W2=th.tensor([[-1,-1,-1],[2,2,2],[-1,-1,-1]],dtype=th.float32).unsqueeze(0).unsqueeze(0)
convFilter2.weight = nn.Parameter(W2)



plt.subplot(1, 3, 1)
plt.imshow(im.squeeze(), cmap='gray')


plt.subplot(1, 3, 2)
plt.imshow(convFilter1(im).squeeze().squeeze().detach().numpy(), cmap='gray')


plt.subplot(1, 3, 3)
plt.imshow(convFilter2(im).squeeze().squeeze().detach().numpy(), cmap='gray')


plt.show()

"""# Pool !

Now we introduce the max-pooling in 2 dimensions: *MaxPool2d*. Look at the documentation and then try to define the following pipeline:
- a convolution with a kernel size of 3, stride 1 and padding 1
- apply the ReLu function and
- a max pooling with kernel size of 2 and a stride of 2.
Try to guess before running your code the dimensions of the output !

"""

# TODO

convFilter = nn.Conv2d(in_channels=1,out_channels=1,
                       kernel_size =3,padding=1)
res=F.relu(convFilter(im))
pool=nn.MaxPool2d(kernel_size=2,stride=2)
res1=pool(res)
plt.subplot(1, 3, 1)
plt.imshow(im.squeeze(), cmap='gray')
plt.subplot(1, 3, 2)
plt.imshow(res.squeeze().detach().numpy(), cmap='gray')
plt.subplot(1, 3, 3)
plt.imshow(res1.squeeze().detach().numpy(), cmap='gray')

"""#  A first model

After this interlude, the goal now is to write a class to implement the model with:

- 2D convolution with (kernel size = 3, padding = 1, stride 1)
- ReLu activation
- Max-pooling (kernel size = 2, stride 2)
- A final linear classifier
- The final activation

Writing this class, allows you to wrap what you have seen so far. To debug the model, you can first play step-by-step with each layer to ensure you obtain the right dimensions (it was done earlier). Then, write the class and run the training to evaluate the result (this what we have to do now).

The class inherits from an existing class of pytorch : *Module*. This mean: it is a *Module*, but we add some peculiarities. For that purpose we can fill the following code:
"""

class FashionCNN(nn.Module):

    def __init__(self, kernel_size = 3, padding= 1, out_channels = 1):
        super(FashionCNN, self).__init__()
        # TODO : write the end of the constructor.
        # It is important to create here all the layers of the network.
        # All layers that have paramaters should be attribute.
        # For example:

        self.conv = nn.Conv2d(in_channels=1, out_channels=out_channels,
                              kernel_size=kernel_size, padding=padding)
        # TODO: add the rest
        self.relu=nn.ReLU()
        self.pool=nn.MaxPool2d(kernel_size=2,stride=2)
        self.flat=nn.Flatten(start_dim=-3, end_dim=-1)
        self.fc=nn.Linear(in_features=out_channels * 14 * 14,out_features=10)
        self.logsoftmax=nn.LogSoftmax(dim=1)



    def forward(self, x):
        # TODO
        # if you need to run forward with the conv layer,
        # you can call it by self.conv
        outconv  = self.conv(x)
        outrelu=self.relu(outconv)
        outpool=self.pool(outrelu)
        outflat=self.flat(outpool)
        outfc=self.fc(outflat)
        output=self.logsoftmax(outfc)
        return output

# Test the class: is everything in place:
# A first classifier is built like :
classif = FashionCNN(out_channels=4)
# The parameters of the classifier are randomly initialize, but we
# can use it on a image :
out = classif.forward(im)([100, 4, 7, 7])
print(out.shape) # the output has 2 dimensions
print(out)

# It is correct ? If not, correct the class to get the expected result.

"""# Training the model

To train the model, we need to define a loss function and an optimizer. For the moment we will rely on an online learning algorithm: online stochastic gradient descent. Like the previous lab session:
- we pick one training example
- compute the loss
- back-propagation of the gradient
- update of the parameters


At the end of one epoch, we evaluate the model on the validation step. You can use for that purpose the training function we wrote earlier.


To train the CNN, we can reuse the training function you wrote carefully in the previous lab session. However we need to adapt it in order to use dataloaders (the `trainloader` and `validloader`)

Question:
- As optimizer we will use *Adam*. It is important to find the good choice of hyper-parameter for the initial learning rate. Try different values like 0.1, 0.01, ...
- Then try with a number of output channel set to 1, 8, 16.


"""

# TODO : paste here the training function you wrote before.
# Of course you can improve it if you want during the lab session.
# Especially in terms of parameters.

def train_model(model, loss_function, optimizer,trainloader
                ,NEpochs):

  Loss=[]
  Accurracy=[]

  for i in range(NEpochs):
    loss2=0
    for X,Y in trainloader:
      X=X.unsqueeze(1)

      model.train()
      Y_pred = model(X)
      loss1 = loss_function(Y_pred,Y)
      loss1.backward()
      optimizer.step()
      optimizer.zero_grad()
      loss2+=loss1.item()
    Loss.append(loss2/len(trainloader))
      ([100, 4, 7, 7])

    acc=0
    for Xvalid,Yvalid in validloader:
      Xvalid=Xvalid.unsqueeze(1)
      model.eval()
      Y=model(Xvalid)
      _, predicted_classes = th.max(Y, dim=1)
      correct = (predicted_classes == Yvalid).sum().item()
      accuracy = correct / len(Xvalid)
      acc+=accuracy
    Accurracy.append(acc/len(validloader))

  plt.subplot(1, 2, 1)
  plt.plot(Loss, label='Loss', color='red', linestyle='-', marker='o', markersize=6)
  plt.title('Loss over Epochs', fontsize=14)
  plt.xlabel('Epochs', fontsize=12)
  plt.ylabel('Loss', fontsize=12)
  plt.grid(True, linestyle='--', alpha=0.6)
  plt.legend(loc='best')

  plt.subplot(1, 2, 2)
  plt.plot(Accurracy, label='Accuracy', color='green', linestyle='-', marker='x', markersize=6)
  plt.title('Accuracy over Epochs', fontsize=14)
  plt.xlabel('Epochs', fontsize=12)
  plt.ylabel('Accuracy', fontsize=12)
  plt.grid(True, linestyle='--', alpha=0.6)
  plt.legend(loc='best')

  plt.tight_layout()
  plt.show()

# TODO
loss_fn=nn.NLLLoss()
model = FashionCNN(out_channels=4)
# Train you model !
optimizer=th.optim.Adam(model.parameters(),lr=0.001)
train_model(model,loss_fn,optimizer,trainloader,10)

"""## Batch-norm

Extend your model to include the Batch-normalization.

"""

# TODO
class FashionCNN(nn.Module):

    def __init__(self, kernel_size = 3, padding= 1, out_channels = 1):
        super(FashionCNN, self).__init__()
        # TODO : write the end of the constructor.
        # It is important to create here all the layers of the network.
        # All layers that have paramaters should be attribute.
        # For example:

        self.conv = nn.Conv2d(in_channels=1, out_channels=out_channels,
                              kernel_size=kernel_size, padding=padding)
        # TODO: add the rest
        self.relu=nn.ReLU()
        self.pool=nn.MaxPool2d(kernel_size=2,stride=2)
        self.flat=nn.Flatten(start_dim=-3, end_dim=-1)
        self.fc=nn.Linear(in_features=out_channels * 14 * 14,out_features=10)
        self.logsoftmax=nn.LogSoftmax(dim=1)
        self.batch=nn.BatchNorm2d(out_channels)



    def forward(self, x):
        # TODO
        # if you need to run forward with the conv layer,
        # you can call it by self.conv
        outconv  = self.conv(x)
        outrelu=self.relu(outconv)
        outpool=self.pool(outrelu)
        outbatch=self.batch(outpool)
        outflat=self.flat(outbatch)
        outbatch=self.batch(outpool)
        outfc=self.fc(outflat)
        output=self.logsoftmax(outfc)
        return output

loss_fn=nn.NLLLoss()
model = FashionCNN(out_channels=4)
# Train you model !
optimizer=th.optim.Adam(model.parameters(),lr=0.001)
train_model(model,loss_fn,optimizer,trainloader,10)

"""## More convolution

We can now define an extended model where the basic block is : Conv2D, ReLu, BatchNorm and MaxPool.
We stack two blocks of this kind before the classification.

For instance in the previous model, this kind of block reduce the image size and increase the number of output channels. We can try to do the same and double this number in the second block.

TODO:
- Implement a model with two blocks as decribed above.
- We can then improve the output classifier.
- Play with the hyper-parameters.

Of course if you want to leverage a deeper model it is useful to increase the amount of training data (we only take the first 30k images until now).
"""

# TODO
# TODO
class FashionCNN(nn.Module):

    def __init__(self, kernel_size = 3, padding= 1, out_channels1 = 1,out_channels2=1):
        super(FashionCNN, self).__init__()
        # TODO : write the end of the constructor.
        # It is important to create here all the layers of the network.
        # All layers that have paramaters should be attribute.
        # For example:

        self.conv1 = nn.Conv2d(in_channels=1, out_channels=out_channels1,
                              kernel_size=kernel_size, padding=padding)
        self.conv2 = nn.Conv2d(in_channels=out_channels1, out_channels=out_channels2,
                              kernel_size=kernel_size, padding=padding)
        # TODO: add the rest
        self.relu=nn.ReLU()
        self.pool=nn.MaxPool2d(kernel_size=2,stride=2)
        self.flat=nn.Flatten(start_dim=-3, end_dim=-1)
        self.fc=nn.Linear(in_features=out_channels2* 14 * 14,out_features=10)
        self.logsoftmax=nn.LogSoftmax(dim=1)
        self.batch1=nn.BatchNorm2d(out_channels1)
        self.batch2=nn.BatchNorm2d(out_channels2)



    def forward(self, x):
        # TODO
        # if you need to run forward with the conv layer,
        # you can call it by self.conv
        outconv1  = self.conv1(x)
        outrelu1=self.relu(outconv1)

        outbatch1=self.batch1(outrelu1)

        outconv2=self.conv2(outbatch1)
        outrelu=self.relu(outconv2)
        outpool=self.pool(outrelu)
        outbatch=self.batch2(outpool)

        outflat=self.flat(outbatch)

        outfc=self.fc(outflat)
        output=self.logsoftmax(outfc)
        return output
loss_fn=nn.NLLLoss()

model = FashionCNN(out_channels1=4,out_channels2=4)
# Train you model !
optimizer=th.optim.SGD(model.parameters(),lr=0.1,momentum=0.9,weight_decay=1e-4)
train_model(model,loss_fn,optimizer,trainloader,30)

"""# And now in color: CIFAR-10


To experiment image classification on a coloured image, we can use the CIFAR-10 dataset.
You can find more details for instance on this page: https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html. We can download the dataset with a dataloader directly:
"""

import torchvision
import torchvision.transforms as transforms

transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

batch_size = 16

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)
trainloader = th.utils.data.DataLoader(trainset, batch_size=batch_size,
                                          shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = th.utils.data.DataLoader(testset, batch_size=batch_size,
                                         shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

"""With this example we will use a **dataset** via a *dataloader*.  This is a convenient tool to handle datasets with efficient iterators."""

def imshow(img):
    img = img / 2 + 0.5     # unnormalize
    npimg = img.numpy()
    plt.imshow(np.transpose(npimg, (1, 2, 0)))
    plt.show()

dataiter = iter(trainloader)
images, labels = dataiter.__next__()
imshow(torchvision.utils.make_grid(images))

"""# Todo

Implement `VGG 16` architecture to get state of the art performance (see the course for the architecture)
"""

class FashionCNN(nn.Module):

    def __init__(self, kernel_size = 3, padding= 1, out_channels1 = 1,out_channels2=1):
        super(FashionCNN, self).__init__()
        # TODO : write the end of the constructor.
        # It is important to create here all the layers of the network.
        # All layers that have paramaters should be attribute.
        # For example:

        self.conv1 = nn.Conv2d(in_channels=3, out_channels=out_channels1,
                              kernel_size=kernel_size, padding=padding)
        self.conv2 = nn.Conv2d(in_channels=out_channels1, out_channels=out_channels2,
                              kernel_size=kernel_size, padding=padding)
        # TODO: add the rest
        self.relu=nn.ReLU()
        self.pool=nn.MaxPool2d(kernel_size=2,stride=2)
        self.flat=nn.Flatten(start_dim=-3, end_dim=-1)
        self.fc=nn.Linear(in_features=out_channels2* 14 * 14,out_features=10)
        self.logsoftmax=nn.LogSoftmax(dim=1)
        self.batch=nn.BatchNorm2d(out_channels2)



    def forward(self, x):
        # TODO
        # if you need to run forward with the conv layer,
        # you can call it by self.conv
        outconv1  = self.conv1(x)
        outconv2=self.conv2(outconv1)
        outrelu=self.relu(outconv2)
        outpool=self.pool(outrelu)
        outbatch=self.batch(outpool)
        outflat=self.flat(outbatch)
        outbatch=self.batch(outpool)
        outfc=self.fc(outflat)
        output=self.logsoftmax(outfc)
        return output

  def train_model(model, loss_function, optimizer,trainloader
                ,NEpochs):

  Loss=[]
  Accurracy=[]

  for i in range(NEpochs):
    loss2=0
    for X,Y in trainloader:
      X=X.unsqueeze(1)

      model.train()
      Y_pred = model(X)
      loss1 = loss_function(Y_pred,Y)
      loss1.backward()
      optimizer.step()
      optimizer.zero_grad()
      loss2+=loss1.item()
    Loss.append(loss2/len(trainloader))


    acc=0
    for Xvalid,Yvalid in testloader:
      Xvalid=Xvalid.unsqueeze(1)
      model.eval()
      Y=model(Xvalid)
      _, predicted_classes = th.max(Y, dim=1)
      correct = (predicted_classes == Yvalid).sum().item()
      accuracy = correct / len(Xvalid)
      acc+=accuracy
    Accurracy.append(acc/len(validloader))

  plt.subplot(1, 2, 1)
  plt.plot(Loss, label='Loss', color='red', linestyle='-', marker='o', markersize=6)
  plt.title('Loss over Epochs', fontsize=14)
  plt.xlabel('Epochs', fontsize=12)
  plt.ylabel('Loss', fontsize=12)
  plt.grid(True, linestyle='--', alpha=0.6)
  plt.legend(loc='best')

  plt.subplot(1, 2, 2)
  plt.plot(Accurracy, label='Accuracy', color='green', linestyle='-', marker='x', markersize=6)
  plt.title('Accuracy over Epochs', fontsize=14)
  plt.xlabel('Epochs', fontsize=12)
  plt.ylabel('Accuracy', fontsize=12)
  plt.grid(True, linestyle='--', alpha=0.6)
  plt.legend(loc='best')

  plt.tight_layout()
  plt.show()