# -*- coding: utf-8 -*-
"""NoteBookBacheletSharkawi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15j09BJ61SWFg7UfUPGy0Kzg2sRJowD65

# INTRODUCTION to PyTorch

This notebook provides a simple introduction to pytorch, assuming you already know **Python, NumPy** and how to use **Jupyter/Colab** notebooks.

**PyTorch** is a Python library designed for **deep learning**. All calculations rely on one type of a fundamental data structure: the **tensor**. A tensor is a generalization of vectors (1 dimension) and matrices (2 dimensions) to higher dimensions. For instance:

- A set of matrices with the same dimensions forms a 3-dimensinal tensor.
- A colored image consists of 3 matrices (one per chanel: red, blue green), making it a tensor.
- A set of images with the same resolution forms a tensor with 4 dimensions

In deep learning everything is represented as tensors: the input data, model parameters, loss functions, gradients, etc. All computations involve operations on tensors, which makes PyTorch very powerful and flexible library for machine learning.


Machine learning basically relies on three key components:

- **The model:** in this course, the model is a Neural Network, which is represented in pytorch as a **Module**.
- **The loss function:** the model is trained to minimize a loss function, which measures how well it performs.
- **The optimizer:** minimization of the loss function is achieved with gradient descent (or one of its variants) using an **optimizer**.

Moreover, to perform gradient descent, we need to compute the gradient of the loss with respect to the model’s parameters. This is the goal of the so-called **auto-differentiation** which provides efficient computation of these gradients.

In this notbook we will introduce these 3 components, along with PyTorch's basic data structure (the tensors) and the concept of auto-differentiation.


To start with pytorch, here are some external websites:
- http://pytorch.org/tutorials/ : official tutorials
- http://pytorch.org/docs/master/ : official documentation

Before you start, check the version of pytorch!
"""

import torch as th
print(th.__version__)
import matplotlib.pyplot as plt
import torch.nn as nn

"""**You should have a version of at least 1.0.0.**

"""

# Need help ?
help(th.arange)

# or, dans un notebook uniquement (syntaxe IPython) :
# ?th.arange

"""# Tensors

In NumPy or MATLAB, you have several methods to create arrays: `zeros`, `ones`, `arange`, `rand`, `randn`... PyTorch uses analogous functions for creating and manipulating tensors, which you will learn how to use. By using these functions, you can easily create tensors and perform various operations on them. For example, PyTorch offers `torch.zeros`, `torch.ones`, `torch.arange`, `torch.rand`, and `torch.randn` to help you initialize tensors in a manner similar to NumPy or MATLAB.



## 1) Operation and access

### **Do the following:**

- Create a Tensor:

        Build a tensor with dimensions 3×4 that is filled with the numbers from 1 to 12.

- Extract Rows and Columns:

        Extract the first row and the last row of the tensor you built.

        Similarly, extract the first column and the last column.

- Matrix Operations with Random Initialization:

        Create matrix A with dimensions 2×3.

        Create matrix B with dimensions 2×1.

        Create matrix C with dimensions 1×4.

        Concatenate matrices A and B (think about the compatibility of the dimensions!!).

        Add the resulting matrix to C.

- Row Selection:

        Create matrix A with dimensions 5×4.

        Create matrix B with dimensions 3×4, such that B is composed of rows from A in this order: the second row, the first row, and the fourth row.
"""

## Your code here ##
#tensor creation
tensor = th.arange(1, 13).reshape(3, 4)
print(tensor)

#column and row extractions
ligne1=tensor[0]
print(ligne1)
dernièreligne=tensor[-1]
colonne1=tensor[:,0]
print(colonne1)
dernièrecolonne=tensor[:,-1]

#matrixoperation
A=th.randn(2,3)
B=th.randn(2,1)
C=th.randn(1,4)

AB=th.cat([A,B],dim=1)
Res=AB + C
print(Res)

#rowselection
A=th.randn(5,4)
B=th.ones(12).reshape(3,4)
B[0,:]=A[1,:]
B[1,:]=A[0,:]
B[2,:]=A[3,:]

"""Look at the following code and how  x2 is built from x. Look at the dimensions of the created tensors."""

x = th.randn(5, 4)
print(x)

x2= th.stack((x,x) , dim=0)
print (x2[0])
print (x2.size())

x2= th.stack((x,x) , dim=1)
print (x2[0])
print (x2.size())

x2= th.stack((x,x) , dim=2)
print (x2[0])
print (x2.size())

"""## 2) Reshape and squeeze

The method `view()` is similar to `reshape` from NumPy. This is **important** since with neural nets, you will often need to manipulate dimensions.

### **Do the following:**

- Build a tensor with dimensions (2, 3, 4).

- Reshape this tensor into two matrices:
    
        One with dimensions (3, 8).
        Another with dimensions (2, 12).

- What does  `view(2,-1)`  do ?
"""

## Your code here
tensor=th.randn(2,3,4)
tensor1=tensor.reshape(3,8)
tensor2=tensor.reshape(2,12)
tensor3=tensor.view(2,-1)
#LE view transorme le tenseur en deux ligne et le -1 fait le calcul atomatiquement de combien de colonne il faut

"""Assume you have a Tensor A of dimensions (3,2,1) that you initialized as you want.

### **Do the following:**

- Read the documentation of the method `squeeze`.

- Try it on A.

- Try the reverse with `unsqueeze`.
"""

## Your code here
A=th.randn(3,2,1)
print(A)
test=A.squeeze()
print(test)
print(test.unsqueeze(2))

"""## 3) Automatic differentiation  (auto-grad)

`torch.autograd` provides classes and functions implementing automatic differentiation.
When a tensor is created with `requires_grad=True`, the object will be able to store information about

- *who has created it,*
- *the gradient, if in the future we decide to compute the gradients of some scalar function.*

In the following example, we build a computational graph. The "end" of this graph must be a scalar for automatic differentiation. Look at the following code.


"""

x = th.randn(1, 1, requires_grad=True)
print("x:",x)
print("x.grad:",x.grad)

"""This tensor `x` has an attribute `grad`, which is initially set to `None`. When you perform operations on `x` using PyTorch functions, a computational graph is being built automatically! This graph keeps track of all operations performed on x and any subsequent tensors derived from it.

The function `backward()` can be called on a tensor that contains a scalar. This call computes the gradients (partial derivatives) of the this scalar value with respect to all the tensors that were involved in its computation. Look at the following code:

"""

y = 2*x+1
print(y)

y.backward()
print(x.grad)

import torch as th

# Créer des tenseurs avec gradient tracking
x = th.tensor([2.0, 3.0], requires_grad=True)
y = th.tensor([1.0, 4.0], requires_grad=True)

# Opérations (graphe computationnel)
z = x * y           # z garde la trace: "créé par x * y"
output = z.sum()    # Scalaire ! (nécessaire pour .backward())

print("Output:", output)  # tensor(14., grad_fn=<SumBackward0>)

# Calculer les gradients
output.backward()

print("Gradient de x:", x.grad)  # dOutput/dx
print("Gradient de y:", y.grad)  # dOutput/dy

"""### **Question:**
*Do you agree with the result ?* (check yourself)
Oui car backward calcul le gradient du scalaire y par rapport à x et le stocke dans x.grad, ici x est un scalaire alors le résultat est directement 2, dans des cas un peu plus compliqué il faut poser le calcul pour prévoir le résultat.

The computational graph can of course be deeper. For instance, we can introduce a new variable `w`, that is a tensor as well.
"""

w = th.randn(1,1, requires_grad=True)
x = th.randn(1, 1, requires_grad=True)

print("w=",w.item()," and x=",x.item())

z = w*x
z.backward()
print(x.grad)
print(w.grad)

"""### **Question:**

*What do you think about the result ?*
Ici ce sont toujours des scalaire alors x.grad renvoie la dérivée partielle de z par rapport à x et donc ici c'est omega et vice versa.

It is worth noticing that the gradient is a tensor operation on a scalar value: **we compute the partial derivative of a scalar quantity w.r.t a tensor**. The variable on which we run the `backward()` method must be a scalar.


### **Question:**

Consider the following code: can you explain the results ?
la variable out est en réalité 1/2(x[00]²+x[01]²+x[10]²+x[11]²) et x.grad renvoie une matrice de la meme taille que x tel que X.grad[ij]=la dérivée partielle de out par rapport à x[ij] donc dans notre cas x.grad=x
"""

x = th.randn(2,2,requires_grad=True)        # x is a square matrix
print(x)
out = 0.5*x.pow(2).sum() # out is a new variable (scalar)
out.backward()           # back propagation in the graph
print("g:",x.grad)       # the gradient of out with respect to x
print("x:",x)            # A simple check. Is it what expected ? oui voir explication ci dessus

"""
### **Question:**

And can you explain this example  ? oui, si on pose le calcul de out x.grad devrait renvoyer la matrice [[a+c,b+d],[a+c,b+d]] en notant x=[[a,b],[c,d]]
ce qui est bien le cas.
"""

x = th.randn(2,2,requires_grad=True)        # x is a square matrix
print(x)
w = th.ones(1,2,requires_grad=True)
print(w)
out = 0.5*(w@x).pow(2).sum() # out is a new variable (scalar)
out.backward()           # back propagation in the graph
print("x:",x)
print("x.grad:",x.grad)  # the gradient of out with respect to x
print("w:",w)
print("w.grad:",w.grad)  # the gradient of out with respect to x

"""## 4) Linear regression with gradient descent

In this section we focus on linear regression, using synthetic data.

The data are generated with the following code:
"""

th.manual_seed(123) # to ensure reproducibility
var= 1 #
X = th.arange(8) + th.randn(8)/var
Y = 2*(th.arange(8) + th.randn(8)/var) + 0.5

_ = plt.scatter(X,Y)

_ = plt.xlabel('x')
_ = plt.ylabel('y')

"""Our goal is to approximate this simple data set with a function $f$ such that
$$
y_i \approx f(x_i).
$$

To find the right set of parameters that define $f$, we want to minimize the mean square error:
$$L = \frac{1}{N} \sum_i^N (f(x_i) - y_i)^2.$$

Our first assumption is that $f$ is a linear function:
$$ f(x) = w\ x+w_0.$$.

The optimization procedure (here: gradient descent) starts with the random initialization of the parameters $(w,w_0)$.
"""

w = th.randn(1,requires_grad=True)
w0= th.randn(1,requires_grad=True)

"""When you plot a linear function $f(x)$ using these randomly chosen parameters $w, w_0$, together with your training points (evaluate the cell belwo), you will see that $f(x)$ does not describe the data very well (or you are very lucky with the random numbers! try again if you are)."""

xs = th.linspace(0,8,2) # need 2 points for a line
plt.plot(xs,(w*xs+w0).detach(),'r', label = 'f(x) using random params')
plt.scatter(X,Y, label = 'data')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.show()

"""### **Do the following:**

Quantify the poor quality of this random initialization by computing the loss function.
"""

## Your code here

Y1=w*X+w0
loss=((Y1-Y).pow(2)).mean()
print(loss)

"""### **Do the following:**

Use the `backward` function to get the gradient of the loss with respect to the parameters.
- Print the gradients.
- Propose an update of the parameters
- Verify if it improves the loss function
"""

## Your code here
loss.backward()
print("dL/dw  =", w.grad.item())
print("dL/dw0 =", w0.grad.item())

# Mise a jour : un pas de descente de gradient, w <- w - lr * dL/dw.
# On l'ecrit dans un bloc no_grad() et avec des operations "in place" (-=) :
#  - no_grad() evite d'enregistrer la mise a jour dans le graphe de calcul
#    (la mise a jour n'est pas une operation qu'on veut deriver) ;
#  - sans cela, "w = w - lr*w.grad" cree un NOUVEAU tenseur, qui n'est plus
#    une feuille du graphe : au backward suivant, w.grad resterait a None.
lr = 0.01
with th.no_grad():
    w  -= lr * w.grad
    w0 -= lr * w0.grad

Y1_new = w * X + w0
loss_new = ((Y1_new - Y).pow(2)).mean()
print("variation de la loss :", (loss_new - loss).item())

#le résultat est négatif on a donc bien diminuer la loss

# Remarque importante : les gradients de PyTorch s'ACCUMULENT.
# Si on refaisait un backward() maintenant sans remettre w.grad a zero,
# le nouveau gradient s'ajouterait a l'ancien. D'ou le zero_grad() du
# paragraphe suivant, qu'on appelle a chaque iteration d'entrainement.
w.grad.zero_()
w0.grad.zero_()

"""## 5) Optimizer and the loss function

The optimizer "takes care" of model parameters update during training. In PyThorch, the base class for all optimizers is `Optimizer`, which is a part of the module `torch.optim`. As you discussed in TD, one commonly used optmizer is Stochastic Gradient Descent `SGD`. Look at the details in its documentation!

In the future, you will also use `Adam`optimizer, but for the moment we are focusing on `SGD`. Note, however, that they all have (more or less) the same interface --- to create an optimizer instance, you need to pass the parameters to be updated and specify the learning rate (lr).

We continue with our concrete problem: to create an optimizer we start by creating an object `SGD` with:

- the parameters under consideration
- the lr parameter,

(see the code below). The parameters we want to learn are `w` and `w0`.
"""

w = th.randn(1,requires_grad=True)
w0= th.randn(1,requires_grad=True)
trainable_parameters = (w,w0)
sgd = th.optim.SGD(trainable_parameters, lr=1)

"""### **Do the following:**

- Explain the parameter `lr`.
lr c'est le pas dans la descente de gradient, une sorte de vitesse de convergence, un trop gros peut empecher de converger un trop petit peut mettre trop de temps à converger il faut trouver un bon compromis

The two important functions you will use are:

- `step()` --- This function updates all trainable parameters using their computed gradients (e.g., w.grad and w0.grad).

- `zero_grad()` --- This function resets the gradient values, preparing them for the next training step.


### **Do the following:**
- Compute Predictions:
        
        Compute the predictions for the input data `X`.

- Backward Propagation:
    
        Do the backpropagation and print the values of `w` and `w0` along with their gradients.

- Update Parameters:
   
        Make an update using the optimizer and print the updated values of `w` and `w0` with their gradients.

- Reset Gradients:
    
        Run `zero_grad()` to reset the gradients and print the values of `w` and `w0` with their gradients after resetting.

- Plot the New Line:
        
        Plot the new line defined by the new values of `w` and `w0`.

- Evaluate Learning Rate:
    
        Do you think value of the learning rate `lr` is adapted for this task ?
"""

## Your code here
w = th.randn(1,requires_grad=True)
w0= th.randn(1,requires_grad=True)
trainable_parameters = (w,w0)

#prediction
sgd = th.optim.SGD(trainable_parameters, lr=0.01)
Y_pred=w*X+w0
loss=((Y_pred-Y).pow(2)).mean()
#backprop
loss.backward()
print("etape1")
print(w)

print(w.grad)
print(w0)
print(w0.grad)
#uptade parameters
sgd.step()
print("etape2")
print(w)

print(w.grad)
print(w0)
print(w0.grad)
#reset gradients
sgd.zero_grad()
print("etape3")
print(w)

print(w.grad)
print(w0)
print(w0.grad)
#plot the new line
xs = th.linspace(0,8,2) # need 2 points for a line
plt.plot(xs,(w*xs+w0).detach(),'r', label = 'Uptaded line')
plt.scatter(X,Y, label = 'data')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.show()
#évalurer le lr
Y_pred_new = w * X + w0
loss_new = ((Y_pred_new - Y).pow(2)).mean()
print((((loss_new-loss)/loss)*100).item())
#un bon lr est si le print est entre 1 et 10 donc ici lr=1 est bien trop grand

"""Many loss functions are already implemented in PyTorch (see https://pytorch.org/docs/stable/nn.html#loss-functions for the full list). In our lab sessions we will focus on:

- `MSELoss` for regression
- `BCELoss` for binary classification
- `CrossEntropyLoss` and `NLLLoss` for multiclass classification


- Read the documentation of these losses and apply the `MSELoss` to the prediction for `X`
- Repeat all the steps from the previous TODO list and include a calculation of the `MSELoss`.
"""

## Your code here : les memes etapes, mais avec nn.MSELoss() au lieu du calcul a la main
w = th.randn(1, requires_grad=True)
w0 = th.randn(1, requires_grad=True)
sgd = th.optim.SGD((w, w0), lr=0.01)
mse = nn.MSELoss()          # <- le module de loss remplace ((Y_pred-Y)**2).mean()

Y_pred = w * X + w0
loss = mse(Y_pred, Y)       # exactement la meme valeur que le calcul manuel
print("MSELoss :", loss.item())
print("verification a la main :", ((Y_pred - Y).pow(2)).mean().item())

loss.backward()
print("avant step  : w =", w.item(), "| grad =", w.grad.item())
sgd.step()
print("apres step  : w =", w.item(), "| grad =", w.grad.item())  # w a bouge, le grad est intact
sgd.zero_grad()
print("apres zero_ : w =", w.item(), "| grad =", w.grad.item())  # le grad est remis a 0

"""Les trois lignes `loss.backward()` / `optimizer.step()` / `optimizer.zero_grad()`
forment le **triptyque** que l'on retrouvera dans absolument tous les TP suivants.
L'ordre compte : on ne peut pas mettre a jour avant d'avoir calcule le gradient,
et il faut remettre les gradients a zero avant l'iteration suivante (sinon ils
s'accumulent).

## 6) The training function

Now you have everything to write the training code of the model!


### **Do the following:**

- Initialize the model parameters before the training begins.

- Perform SGD in a loop: iterate over multiple epochs, updating parameters using the optimizer.

- Record how the loss evolves after each epoch.

- Plot the loss evolution during the training process.

- Plot the new decision boundary and observe how it changed during training.
"""

Nepoch = 10
lr = 0.01

## Your code here
def training(X, Y, Nepoch=100, lr=0.01, verbose=False):
    """Regression lineaire par descente de gradient, ecrite "a la main".

    Args:
        X, Y   : tenseurs 1D de meme longueur (les donnees)
        Nepoch : nombre de passages sur les donnees
        lr     : learning rate
    Returns:
        (w, w0, Loss) : les parametres appris et l'historique de la loss
    """
    w = th.randn(1, requires_grad=True)
    w0 = th.randn(1, requires_grad=True)
    sgd = th.optim.SGD((w, w0), lr=lr)

    Loss = []
    for epoch in range(Nepoch):
        Y_pred = w * X + w0                    # 1. forward
        loss = ((Y_pred - Y).pow(2)).mean()    # 2. loss
        Loss.append(loss.item())

        loss.backward()                        # 3. backward : calcul des gradients
        sgd.step()                             # 4. mise a jour des parametres
        sgd.zero_grad()                        # 5. remise a zero des gradients

        if verbose and epoch % max(1, Nepoch // 10) == 0:
            print(f"epoch {epoch:4d} | loss = {loss.item():.4f}")
    return w, w0, Loss


def plot_training(X, Y, w, w0, Loss, title=""):
    """Affiche cote a cote la courbe de loss et la droite apprise."""
    fig, axs = plt.subplots(1, 2, figsize=(11, 4))
    axs[0].plot(Loss)
    axs[0].set_xlabel("epoch"); axs[0].set_ylabel("loss (MSE)")
    axs[0].set_title("Evolution de la loss"); axs[0].grid(alpha=.3)

    xs = th.linspace(0, 8, 2)                  # 2 points suffisent pour une droite
    axs[1].plot(xs, (w * xs + w0).detach(), 'r', label='droite apprise')
    axs[1].scatter(X, Y, label='donnees')
    axs[1].set_xlabel('x'); axs[1].set_ylabel('y')
    axs[1].set_title("Modele appris"); axs[1].legend(); axs[1].grid(alpha=.3)
    fig.suptitle(title)
    plt.tight_layout(); plt.show()


w, w0, Loss = training(X, Y, Nepoch=Nepoch, lr=lr, verbose=True)
plot_training(X, Y, w, w0, Loss, title=f"Nepoch={Nepoch}, lr={lr}")
print("loss initiale :", Loss[0], "| loss finale :", Loss[-1])

"""Avec seulement 10 epochs la droite n'a pas eu le temps de converger.
On relance beaucoup plus longtemps pour verifier que le modele retrouve bien
les parametres qui ont servi a generer les donnees (w ~ 2, w0 ~ 0.5) :
"""

w, w0, Loss = training(X, Y, Nepoch=500, lr=0.01)
plot_training(X, Y, w, w0, Loss, title="Nepoch=500, lr=0.01")
print(f"w = {w.item():.3f} (attendu ~2)   w0 = {w0.item():.3f} (attendu ~0.5)")

"""Comparaison de plusieurs learning rates sur le meme probleme.
On voit le compromis classique : trop petit -> convergence lente ;
trop grand -> la loss oscille voire diverge.
"""

plt.figure(figsize=(7, 4))
for lr_test in [0.001, 0.01, 0.05, 0.1]:
    th.manual_seed(0)                       # meme initialisation pour comparer
    _, _, L = training(X, Y, Nepoch=200, lr=lr_test)
    plt.plot(L, label=f"lr = {lr_test}")
plt.yscale("log")                           # echelle log : les ecarts sont enormes
plt.xlabel("epoch"); plt.ylabel("loss (MSE, echelle log)")
plt.title("Influence du learning rate"); plt.legend(); plt.grid(alpha=.3)
plt.show()

"""## 7) Module

In the previous section we coded our linear model "by hand". In practice, it is more convenient to use existing modules (base class `Module`). For instance the linear transform $f(x) = wx+w_0$ is simply the application of a so-called `Linear` module.

### **Do the following:**

- Look at the documentation

- Rewrite the training code such that it uses a `Linear` module.

- Look at the result.
"""

import torch.nn as nn

#DATA
th.manual_seed(123) # to ensure reproducibility
var= 1 #
X = th.arange(8) + th.randn(8)/var
Y = 2*(th.arange(8) + th.randn(8)/var) + 0.5



#reshape
X = X.view(-1, 1)  # IMPORTANT: reshape en (8, 1) pour nn.Linear
Y = Y.view(-1, 1)

#training+model
Nepoch = 500
lr = 0.01

model = nn.Linear(1, 1)          # equivaut a f(x) = w*x + w0, mais w et w0 sont geres par le module
sgd = th.optim.SGD(model.parameters(), lr=lr)
mse = nn.MSELoss()

Loss = []
for i in range(Nepoch):
    Y_pred = model(X)
    loss = mse(Y_pred, Y)
    Loss.append(loss.item())
    loss.backward()
    sgd.step()
    sgd.zero_grad()

# ATTENTION : ici la droite doit etre tracee avec les parametres DU MODELE
# (model.weight / model.bias), et surtout pas avec les w, w0 des cellules
# precedentes qui n'ont plus rien a voir avec cet entrainement.
fig, axs = plt.subplots(1, 2, figsize=(11, 4))
axs[0].plot(Loss); axs[0].set_xlabel("epoch"); axs[0].set_ylabel("loss")
axs[0].set_title("Loss (module nn.Linear)"); axs[0].grid(alpha=.3)

xs = th.linspace(0, 8, 2).view(-1, 1)   # (2,1) : nn.Linear attend un batch
with th.no_grad():                      # pas besoin du graphe pour un simple trace
    ys = model(xs)
axs[1].plot(xs, ys, 'r', label='droite apprise')
axs[1].scatter(X, Y, label='data')
axs[1].set_xlabel('x'); axs[1].set_ylabel('y'); axs[1].legend(); axs[1].grid(alpha=.3)
axs[1].set_title("Modele nn.Linear")
plt.tight_layout(); plt.show()

# Les parametres appris sont exactement les memes qu'a la main :
print("w  (model.weight) =", model.weight.item())
print("w0 (model.bias)   =", model.bias.item())

# Un Module expose ses parametres, ce qui evite de les lister soi-meme
# quand le modele devient gros (c'est tout l'interet) :
for name, p in model.named_parameters():
    print(f"{name:12s} shape={tuple(p.shape)}  requires_grad={p.requires_grad}")
print("Nombre total de parametres :", sum(p.numel() for p in model.parameters()))

"""## 8) Logistic Regression

Let start with an easy dataset for binary classification. The following subsections just provide a synthetic dataset and a function to visualize it.



### 8.1)  Create the data

"""

import numpy as np
ST1 = np.array([[17.0 ,12 ,13 ,15 ,15 ,20 ,20],[ 10 ,12 ,14 ,15 ,20 ,15 ,20]]) # class 1
ST2 = np.array([4, 7.5, 10 ,11, 5 ,5 ,6, 8, 5, 0, 5, 0, 10, 6]).reshape(2,7) # class 2
Xstudents = np.concatenate((ST1,ST2),axis=1)
Ystudents = np.ones(14)
Ystudents[7:] = 0

"""### **Do the following:**

- Plot the dataset with two colors (one for each class).

"""

classe1=Xstudents[:,Ystudents==1] #je prends les notes au deux exam de la classe 1
classe2=Xstudents[:,Ystudents==0]
plt.scatter(classe1[0],classe1[1],s=100,color='g',label='classe1(reussite)',marker='o')
plt.scatter(classe2[0],classe2[1],s=100,color='r',label='classe2(echec)',marker='+')
plt.xlabel('note premier exam' )
plt.ylabel('note deuxième exam ')
plt.legend()

"""### 8.2) The model


In this section, you will define, train, and visualize a logistic regression model using PyTorch.


The roadmap is:

- Convert Data to Tensors:

        As explained PyTorch models utilises Tensor objects. Make sure that your dataset is converted into PyTorch tensors before training.

- Create the Logistic Regression Model:

        Use `torch.nn.Sequential` to define a simple neural model. The model should consist of a single neuron with a logistic activation function (i.e., a linear layer followed by a sigmoid function).

- Define the Optimizer:

        Take the basic Stochastic Gradient Descent (SGD) as the optimization algorithm.

- Define the Objective (Loss) Function

- Train the Model:

        Implement a training loop that iterates until convergence. It can be useful to play with different learning rates to observe their effects. Perform gradient descent step-by-step, updating the model parameters after each example.

- Look at the solution:

        Visualize the decision boundary and check how well the model has learned.

- Train in Batch Mode:

        Start again in **batch** mode -- instead of updating the model after each example, compute gradients using the entire training set.


### **Do all the things in the list above**

#### From data to tensors / variables

"""

## Your code here
X = th.tensor(Xstudents.T, dtype=th.float32)
Y = th.tensor(Ystudents, dtype=th.float32).view(-1, 1)

"""#### Create the model, its loss and optimizer

The model is a linear transformation followed by a Sigmoid function. This is equivalent to a logistic regression model.
"""

# The model
D_in=2  # input size : 2
D_out=1 # output size: one value

model = nn.Sequential(nn.Linear(D_in, D_out), nn.Sigmoid())
lr = 0.01
optimizer = th.optim.SGD(model.parameters(), lr=lr)

# BCELoss = Binary Cross Entropy : la loss de la classification binaire.
#   L = -[ y*log(p) + (1-y)*log(1-p) ],  avec p = sortie du Sigmoid
# Elle ATTEND des probabilites (donc un Sigmoid avant), contrairement a
# BCEWithLogitsLoss qui prend les logits bruts et integre le sigmoid
# (numeriquement plus stable : c'est ce qu'on utilise en pratique).
criterion = nn.BCELoss()
loss_fn = criterion          # alias utilise dans les cellules de test ci-dessous

"""#### Testing the model with data
You can run inference to see if everything is fine.

"""

# With a single input vector
prediction = model(X[0]) # or prediction = model.forward(X[0]) both are equivalent

print("For the first input: ",prediction)

# With 3 input vectors
prediction = model(X[0:3])
print("For the 3 first inputs: ",prediction)

# For the whole dataset
prediction = model(X)
print("For all: ",prediction)

# With a single input vector
prediction = model(X[0])
print("The first prediction: ",prediction, prediction.shape)
print("The reference: ",Y[0], Y[0].shape)

loss_fn(prediction,Y[0])

"""This code should generate a warning or an error, since the label (or target value) and the prediction (considered as the input value of the loss) are of different dimensions.

There is two ways to fix this. The first one is to reduce the input dimension using `squeeze`. The second one is to modify the target values. See the two cells below.
"""

prediction = model(X[0]).squeeze()
print("The first prediction: ",prediction, prediction.shape)
print("The reference: ",Y[0], Y[0].shape)

loss_fn(prediction,Y[0])

prediction = model(X[0])
Ymodified = Y.view(-1,1)
print("The first prediction: ",prediction, prediction.shape)
print("The reference: ",Ymodified[0], Ymodified[0].shape)

loss_fn(prediction,Ymodified[0])

"""#### Training loop

"""

## Your code here
Nepochs = 500
Loss_stochastic = []

for epoch in range(Nepochs):
    epoch_loss = 0

    # Passer sur chaque exemple un par un
    for i in range(len(X)):
        # Prédiction pour 1 exemple
        x_i = X[i:i+1]  # Shape: (1, 2)
        y_i = Y[i:i+1]  # Shape: (1, 1)

        y_pred = model(x_i)
        loss = criterion(y_pred, y_i)

        # Backward + Update
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        epoch_loss += loss.item()

    Loss_stochastic.append(epoch_loss / len(X))

"""It is better to visualize the evolution of the loss function: to be sure that everything went well. The idea is to store the loss values in a numpy array and then to plot it.

####  Plot the solution
"""

## Your code here
#je me suis aidé d'une IA ici car je n'arrivais pas a plot ma frontière mais je pense avoir compris le principe pour les TP
def plot_decision_boundary(model, X, Y, title):
    plt.figure(figsize=(10, 6))

    # Points
    classe_1 = X[Y.flatten() == 1]
    classe_0 = X[Y.flatten() == 0]

    plt.scatter(classe_1[:, 0], classe_1[:, 1], s=100, c='green',
                label='Classe 1 (Réussite)', marker='o', edgecolors='black')
    plt.scatter(classe_0[:, 0], classe_0[:, 1], s=100, c='red',
                label='Classe 0 (Échec)', marker='x', linewidths=2)

    # Frontière de décision
    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    xx, yy = th.meshgrid(th.linspace(x_min, x_max, 200),
                         th.linspace(y_min, y_max, 200))

    grid = th.cat([xx.reshape(-1, 1), yy.reshape(-1, 1)], dim=1)

    with th.no_grad():
        Z = model(grid).reshape(xx.shape)

    plt.contour(xx, yy, Z, levels=[0.5], colors='blue', linewidths=2)
    plt.contourf(xx, yy, Z, levels=[0, 0.5, 1], colors=['#ffcccc', '#ccffcc'], alpha=0.3)

    plt.xlabel('Note Exam 1', fontsize=12)
    plt.ylabel('Note Exam 2', fontsize=12)
    plt.title(title, fontsize=14)
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()

plot_decision_boundary(model, X, Y, 'Mode Stochastique')

"""#### Explore the "solution"

Here, we look at the different wrapping steps:
- The model is a set of modules
- A Linear module is a matrix of weights along with a bias vector. They are parameters.
- A Parameter wrap a tensor
- A tensor can be casted as a numpy array

"""

mod = model[0]
print(type(mod))
print(type(mod.bias))
print(type(mod.bias.data))
print(type(mod.bias.data.numpy()))

"""We can look at the parameters:"""

print(mod.bias.data.view(1,1))
print(mod.weight.data)

"""#### Impact of the learning rate

Now, we will use the same model, but trained with a different learning rate. The training process restarts from scratch. We need to therefore re-create the model and the associated optimizer.
"""

model = th.nn.Sequential(
    th.nn.Linear(D_in, D_out),
    th.nn.Sigmoid()
)
learning_rate = 1e-1
optimizer = th.optim.SGD(model.parameters(), lr=learning_rate)

"""Now that we have the model, with randomly initialized parameters, we can train it using a different learning rate --- a larger one.

#### **Do the following:**

- Run the training with the same number of epochs and compare the loss value we get at the end
- Do you think we can reach the same value with the learning rate of 1e-2, but with a longer training ?
- Try the same thing with a learning rate of 0.5, what do you observe ?


"""

## Your code here
def train_logistic(X, Y, lr=0.01, Nepochs=500, mode="stochastic", seed=0):
    """Entraine une regression logistique et renvoie (model, historique de loss).

    mode = "stochastic" : une mise a jour par exemple (online / SGD pur)
    mode = "batch"      : une seule mise a jour par epoch, sur tout le dataset
    """
    th.manual_seed(seed)                      # meme init pour toutes les comparaisons
    model = nn.Sequential(nn.Linear(D_in, D_out), nn.Sigmoid())
    optimizer = th.optim.SGD(model.parameters(), lr=lr)
    criterion = nn.BCELoss()

    Loss = []
    for epoch in range(Nepochs):
        if mode == "stochastic":
            epoch_loss = 0.0
            for i in range(len(X)):
                y_pred = model(X[i:i+1])      # X[i:i+1] et pas X[i] : il faut garder la dim de batch
                loss = criterion(y_pred, Y[i:i+1])
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()
                epoch_loss += loss.item()
            Loss.append(epoch_loss / len(X))
        elif mode == "batch":
            y_pred = model(X)                 # tout le dataset d'un coup
            loss = criterion(y_pred, Y)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            Loss.append(loss.item())
        else:
            raise ValueError("mode doit valoir 'stochastic' ou 'batch'")
    return model, Loss


def accuracy(model, X, Y):
    """Taux de bonne classification (seuil de decision a 0.5)."""
    with th.no_grad():
        pred = (model(X) > 0.5).float()
    return (pred == Y).float().mean().item()

"""#### Mode stochastique *vs* mode batch

Meme modele, meme learning rate, meme nombre d'epochs : seule la **granularite
de la mise a jour** change.

- **stochastique** : 14 mises a jour par epoch (une par etudiant) ;
- **batch** : 1 seule mise a jour par epoch, calculee sur les 14 exemples.

A nombre d'epochs egal, le mode stochastique avance donc 14 fois plus vite en
nombre de pas, ce qui se voit tout de suite sur la courbe. En contrepartie sa
courbe est plus bruitee : chaque pas suit le gradient d'un seul exemple, qui
n'est qu'une estimation tres bruitee du "vrai" gradient.
"""

model_sto, Loss_sto = train_logistic(X, Y, lr=0.01, Nepochs=500, mode="stochastic")
model_bat, Loss_bat = train_logistic(X, Y, lr=0.01, Nepochs=500, mode="batch")

plt.figure(figsize=(7, 4))
plt.plot(Loss_sto, label=f"stochastique (acc={accuracy(model_sto, X, Y):.2f})")
plt.plot(Loss_bat, label=f"batch        (acc={accuracy(model_bat, X, Y):.2f})")
plt.xlabel("epoch"); plt.ylabel("BCE loss")
plt.title("Stochastique vs batch, lr = 0.01"); plt.legend(); plt.grid(alpha=.3)
plt.show()

plot_decision_boundary(model_sto, X, Y, 'Mode stochastique')
plot_decision_boundary(model_bat, X, Y, 'Mode batch')

"""#### Impact du learning rate

On reprend le mode batch et on ne fait varier que `lr`.
"""

plt.figure(figsize=(7, 4))
resultats = {}
for lr_test in [1e-2, 1e-1, 0.5]:
    m, L = train_logistic(X, Y, lr=lr_test, Nepochs=500, mode="batch")
    resultats[lr_test] = (m, L)
    plt.plot(L, label=f"lr = {lr_test}  (loss finale = {L[-1]:.3f})")
plt.xlabel("epoch"); plt.ylabel("BCE loss")
plt.title("Influence du learning rate (mode batch)"); plt.legend(); plt.grid(alpha=.3)
plt.show()

for lr_test, (m, L) in resultats.items():
    print(f"lr = {lr_test:<5} | loss finale = {L[-1]:.4f} | accuracy = {accuracy(m, X, Y):.3f}")

"""#### Reponses aux questions

**1. Compare la loss finale pour les differents learning rates.**
Plus le learning rate est grand, plus la loss descend vite *au debut*. Avec
`lr = 1e-2` la loss est encore loin de son minimum au bout de 500 epochs :
le pas est trop petit pour la courbure du probleme.

**2. Peut-on atteindre la meme valeur avec `lr = 1e-2` mais un entrainement plus long ?**
Oui. Ici la loss est convexe (regression logistique = probleme convexe), il n'y
a donc **qu'un seul minimum** et tout learning rate suffisamment petit finit par
l'atteindre. Le learning rate ne change pas *ou* on converge, seulement *en
combien de temps*. C'est une propriete de ce probleme precis : des qu'on aura
des reseaux profonds (donc des loss non convexes), le learning rate influencera
aussi *vers quel* minimum on tombe.

**3. Avec `lr = 0.5` ?**
La descente est beaucoup plus rapide, et sur ce jeu de donnees elle reste
stable car la loss logistique a un gradient borne (le sigmoid sature). Sur un
probleme moins bien conditionne, un pas aussi grand ferait osciller la loss,
voire diverger : on "saute" par-dessus le minimum a chaque pas.

Un dernier point important : les notes brutes vont de 0 a 20 et ne sont pas
normalisees. Les gradients selon les deux features sont donc d'echelles tres
differentes, ce qui rend la surface de loss allongee et ralentit la descente.
Normaliser les entrees (moyenne 0, ecart-type 1) est presque toujours une bonne
idee - c'est exactement ce qu'on fera dans le TP meteo.
"""

Xn = (X - X.mean(dim=0)) / X.std(dim=0)      # whitening des deux features
model_n, Loss_n = train_logistic(Xn, Y, lr=0.01, Nepochs=500, mode="batch")

plt.figure(figsize=(7, 4))
plt.plot(Loss_bat, label="donnees brutes")
plt.plot(Loss_n, label="donnees normalisees")
plt.xlabel("epoch"); plt.ylabel("BCE loss")
plt.title("Effet de la normalisation des entrees (lr = 0.01, batch)")
plt.legend(); plt.grid(alpha=.3); plt.show()

print(f"loss finale brute       : {Loss_bat[-1]:.4f}  (acc = {accuracy(model_bat, X, Y):.3f})")
print(f"loss finale normalisee  : {Loss_n[-1]:.4f}  (acc = {accuracy(model_n, Xn, Y):.3f})")
