# -*- coding: utf-8 -*-
"""Copie de ODL_lab_recurrent_meteo_2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ypyuoG6-dj68bWxGbo4c0S0psK5p-mG
"""

import numpy as np
import matplotlib.pyplot as plt
import torch  as th
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

"""# Introduction
The SYNOP meteorological data, can be found on [this site](https://public.opendatasoft.com) and if you want more details [go to this page](https://public.opendatasoft.com/explore/dataset/donnees-synop-essentielles-omm/information/?sort=date). We will a prepared dataset which contains a set of measurements (temperature, pressure, ...) made every 3 hours at the ORLY airport.The objective will be to predict the evolution of the weather ! We will start by building a simple model. The idea is to learn the weather of the next day.

## Reminder

Recurrent networks in *pytorch* expects as input a Tensor in 3 dimensions (*3D tensor*). The axes carry an important semantic:
- the first axis is the mini-batch
- the second one corresponds to  "the time"
- the third corresponds to the dimension of input vectors (typically the embedding size or the number of input channels)


Therefore, a sequence of 5 vectors of 4 features (size 4) is represented as a Tensor of dimensions (1,5,4). If we have 7 sequences of 5 vectors, all of size 4, we get (7,5,4) (aside note: in some example,  the first two dimensions can be swapped).  

Lets start with some simple code with synthetic data. The goal is to "play" with the recurrent network, to understand the dimensions and how it works.

"""

th.manual_seed(1) # To reproduce the experiments
inputs = th.randn((1,5,4))
print("input sequence :", inputs)
print("The shape : ", inputs.shape)

"""# A simple recurrent model and  LSTM

A simple recurrent network is for instance of the the **nn.RNN**.
To build it, we must specify:
- the input size (this implies the size of the Linear Layer that will process input vectors);
- the size of the hidden layer (this implies the size of the Linear Layer that will process the time transition).

Other options are available and useful, like:
- nonlinearity
- bias
- batch_first


The forward function of a recurrent net can handle two types of input and therefore acts in two ways.

## One step forward
The first one corresponds to one time step: the neural networks reads one input symbol and update the hidden layer. The forward function therefore returns a tuple of two Tensors: the output and the updated hidden layer.


"""

recNN = nn.RNN(input_size=4, hidden_size=3,batch_first=True)  # Input dim is 4, hidden layer size  is 3

# initialize the hidden state.
# The hidden units initialisation must adapt to data dimensions,
# including the mini-batch dimension.
h0 = th.randn(1, 1, 3)
print("h0 : ",h0,h0.shape)

# One step
print(inputs[0,0,:].view(1,1,-1))
out, hn = recNN(inputs[0,0,:].view(1,1,-1), h0)
# The view is just to ensure 3 dimensions. Try without !
print("##################")
print("One step returns: ")
print("  1/  output : ", out, out.shape)
print("  2/  hidden : ", hn, hn.shape)
print("##################")

"""We can observe that both vectors are the same. Indeed, in a simple recurrent network there is no distinction between the output and the hidden layers.  A prediction can be done by taking into account at each time step this hidden layer:

$$ h_t = f_1(x_t,h_{t-1})$$
$$ y_t = f_2(h_t)$$

For one step forward, the recurrent net only needs to keep track of the hidden layer. The more advanced cell called **LSTM** uses  two kinds of hidden layers: one for the memory managment  named **cell state** (or $c_t$), and the other to make the prediction named  **hidden state** (or $h_t$). The API is almost generic for all the recurrent nets and returns a tuple at each time step. This tuple gathers the sufficient data to unfold the network.
"""

## LSTM
LSTM_NN = nn.LSTM(input_size=4, hidden_size=3, batch_first=True)  # Input dim is 4, hidden layer size  is 3
h0 =  th.randn(1, 1, 3) #
c0 =  th.randn(1, 1, 3) #
print(h0)
# One step
out, (hn,cn) = LSTM_NN(inputs[0,0,:].view(1,1,-1), (h0,c0))
print("##################")
print("One step returns: ")
print("  1/  output : ", out, out.shape)
print("  2/  hidden : ", hn, hn.shape)
print("  3/  cell   : ", cn, cn.shape)
print("##################")

"""## Sequence forward (unfold)
The second "style" of the forward function consists in taking as input a sequence and to unfold the network on this input sequence. It is equivalent to a for loop.
"""

# Process the whole sequence in one call: unfolding the network
outputs, hn = recNN(inputs, h0)
print("* outputs:\n",outputs, "\n  shape:",outputs.shape,"\n")
print("* hn:\n",hn, "\n  shape:",hn.shape)

"""in this case, the forward function returns:
- the sequence of the hidden layers associated to each input vector;
- and the last hidden layer.
The previous code is to some extent equivalent to this one:
"""

hn=h0 # init
print("----------------------")
print(inputs)
print("----------------------")

for t in range(inputs.shape[1]):
    print(inputs[0,t])
    out, hn = recNN(inputs[0,t].view(1,1,-1), hn)
    print("at time ",t, " out = ", out)

"""# Usage of GRU and LSTM

## GRU (Gated Recurrent Unit)

A **GRU** (Gated Recurrent Unit) is a recurrent neural network cell designed to improve over vanilla RNNs when modeling **long-term dependencies**.  
It introduces **gates** (learned soft switches) that control how much past information should be kept and how much new information should be injected.

### GRU state

A GRU has a **single** internal state:

- **hidden state**: $h_t \in \mathbb{R}^{H}$

### GRU equations

Given an input $x_t$ and the previous hidden state $h_{t-1}$:

- **Update gate**
$$
z_t = \sigma(W_z x_t + U_z h_{t-1} + b_z)
$$

- **Reset gate**
$$
r_t = \sigma(W_r x_t + U_r h_{t-1} + b_r)
$$

- **Candidate hidden state**
$$
\tilde{h}_t = \tanh\!\left(W_h x_t + U_h (r_t \odot h_{t-1}) + b_h\right)
$$

- **New hidden state**
$$
h_t = (1 - z_t)\odot h_{t-1} + z_t \odot \tilde{h}_t
$$

### Intuition

- The **update gate** $z_t$ controls *how much we overwrite* the previous hidden state:
  - $z_t \approx 0$: keep the old memory
  - $z_t \approx 1$: replace it with the new candidate state

- The **reset gate** $r_t$ controls *how much past information* is used to build the candidate:
  - $r_t \approx 0$: ignore the past (fresh start)
  - $r_t \approx 1$: fully use the past

### In PyTorch

A GRU returns:

- `outputs`: all hidden states $(h_1, \dots, h_T)$
- `hn`: final hidden state $(h_T)$

```python
outputs, hn = nn.GRU(...)(inputs, h0)
```

## LSTM (Long Short-Term Memory)

An **LSTM** (Long Short-Term Memory) is a gated recurrent network that is especially effective for **long-term dependencies**.  
Compared to a GRU, it introduces a second internal state called the **cell state**, which acts as a dedicated long-term memory.

### LSTM states

An LSTM maintains **two** internal states:

- **hidden state**: $h_t \in \mathbb{R}^{H}$ (what the model outputs at each step)
- **cell state**: $c_t \in \mathbb{R}^{H}$ (long-term memory)

### LSTM equations

Given an input $x_t$, previous hidden state $h_{t-1}$, and previous cell state $c_{t-1}$:

- **Input gate**
$$
i_t = \sigma(W_i x_t + U_i h_{t-1} + b_i)
$$

- **Forget gate**
$$
f_t = \sigma(W_f x_t + U_f h_{t-1} + b_f)
$$

- **Output gate**
$$
o_t = \sigma(W_o x_t + U_o h_{t-1} + b_o)
$$

- **Candidate cell content**
$$
\tilde{c}_t = \tanh(W_c x_t + U_c h_{t-1} + b_c)
$$

- **New cell state**
$$
c_t = f_t \odot c_{t-1} + i_t \odot \tilde{c}_t
$$

- **New hidden state**
$$
h_t = o_t \odot \tanh(c_t)
$$

### Intuition

- The **forget gate** $f_t$ decides what fraction of the *old memory* to keep.
- The **input gate** $i_t$ decides how much *new information* enters the memory.
- The **output gate** $o_t$ decides how much of the memory is exposed as the hidden state $h_t$.

The main benefit: the cell state $c_t$ can carry information over long sequences with less degradation than a vanilla RNN.

### In PyTorch

An LSTM returns:

- `outputs`: all hidden states $(h_1, \dots, h_T)$
- `hn`: final hidden state $(h_T)$
- `cn`: final cell state $(c_T)$

```python
outputs, (hn, cn) = nn.LSTM(...)(inputs, (h0, c0))
```

## Recap: RNN vs GRU vs LSTM

| Model | Internal states | Gating? | Long-term dependencies | PyTorch call |
|------:|------------------|:------:|:------------------------|--------------|
| **RNN** | $h_t$ | No | Difficult | `outputs, hn = recNN(inputs, h0)` |
| **GRU** | $h_t$ | Yes | Better | `outputs, hn = gru(inputs, h0)` |
| **LSTM** | $h_t, c_t$ | Yes | Strong (classic) | `outputs, (hn, cn) = lstm(inputs, (h0, c0))` |

### Practical note (important!)

- **GRU** uses only a hidden state $h_t$, so the initial state is just `h0`.
- **LSTM** needs **two** initial states: `h0` (hidden) **and** `c0` (cell).

This is why LSTM calls in PyTorch look different from RNN/GRU calls.

---

## TODO (GRU & LSTM)

- [ ] Replace the RNN with a **GRU** and run the same code.
- [ ] Replace the GRU with an **LSTM** and run the same code.
- [ ] Print and compare the output shapes (`outputs`, `hn`, and `cn` for LSTM).

---
"""

outputs, hn = recNN(inputs, h0)
print("outpout RNN :",outputs)
print("hn RNN :",hn)

## GRU
Gru_nn = nn.GRU(input_size=4, hidden_size=3,batch_first=True)
out, hn = Gru_nn(inputs, h0)
print("outpout GRU :",out)
print("hn GRU :",hn)

c0 =  th.randn(1, 1, 3) #
print(c0)
## LSTM
LSTM_nn = nn.LSTM(input_size=4, hidden_size=3,batch_first=True)
out, (hn,cn) = LSTM_nn(inputs, (h0,c0))
print("outpout LSTM :",out)
print("hn LSTM :",hn)
print("cn LSTM :",cn)

"""# Data set : weather forecast
The dataset comes from this [open data site](https://public.opendatasoft.com/explore/dataset/donnees-synop-essentielles-omm/table/?sort=date&refine.nom=ORLY). After a filtering step and feature selection we end up with the following features (in French):  
- Pression au niveau mer
- Variation de pression en 3 heures
- Direction du vent moyen 10 mn
- Vitesse du vent moyen 10 mn
- Température
- Point de rosée
- Humidité

"""

from google.colab import drive
drive.mount('/content/drive')

train = np.load("/content/drive/MyDrive/meteo-train.py.npy",allow_pickle=True)
test  = np.load("/content/drive/MyDrive/meteo-test.py.npy",allow_pickle=True)

"""---

## TODO

- [ ] Explore the data, look at the values, their respective scales, ...  and create Tensors with the useful part (we can skip the date, for pytorch).
- [ ] Given the different scales involved, it is more efficient to normalize the data: compute the mean and variance for each component on the training set and whiten the datasets.  
"""

Xtrain = train[:, 1:].astype(float)
Xtest = test[:, 1:].astype(float)

mean = Xtrain.mean(axis=0)

std = Xtrain.std(axis=0)

train_normalized = (Xtrain - mean) / std
test_normalized = (Xtest - mean) / std
Xtrain_norm = th.FloatTensor(train_normalized)
Xtest_norm = th.FloatTensor(test_normalized)

temps=np.linspace(0,len(train_normalized),len(train_normalized))
plt.plot(temps,Xtrain_norm)

"""## Reshaping the data

We want to train the recurrent network with mini-batches of size *bsz*. To make it simple we consider all the sequences in the mini-batch have the same size: *ls=16* time steps.

---

## TODO

- [ ] write a function that takes the traindata and transforms it in a Tensor of size (B,L=16,7);
- [ ] test it to be sure everything is correct (you can try to plot some subparts for instance).
"""

def make_sequences(tenseur,L):
    T,D=tenseur.shape
    chunk=L+1
    B=T//chunk
    usable_times=B*chunk
    data=tenseur[:usable_times]
    data=data.view(B,chunk,D)
    X=data[:,:L,:]
    y=data[:,1:,:]
    return X,y

ls = 16
Xtrain_reshaped, ytrain_reshaped = make_sequences(Xtrain_norm, ls)
Xtest_reshaped, ytest_reshaped = make_sequences(Xtest_norm, ls)

print(f"X train shape: {Xtrain_reshaped.shape}")
print(f"y train shape: {ytrain_reshaped.shape}")

# Vérification du décalage (y doit être X décalé de 1)
print("Vérification du décalage (doit être True):", th.equal(Xtrain_reshaped[0, 1:], ytrain_reshaped[0, :-1]))

# Vérification visuelle d'une séquence
# On affiche par exemple la température (index 4) de la première séquence
plt.figure(figsize=(10, 4))
plt.plot(Xtrain_reshaped[0, :, 4], marker='o', label='Séquence 0 (X)')
plt.plot(range(1, 17), ytrain_reshaped[0, :, 4], marker='.', linestyle='--', label='Séquence 0 (y - cible)')
plt.title("Vérification de l'alignement X et y (Température)")
plt.xlabel("Pas de temps")
plt.ylabel("Valeur normalisée")
plt.legend()
plt.grid(True)
plt.show()

print(f"Valeur max dans le train X: {Xtrain_reshaped.max():.2f}")
print(f"Valeur min dans le train X: {Xtrain_reshaped.min():.2f}")

"""# Recurrent model
The idea is to train a recurrent model that can predict the weather of the next day given the past observation.
To learn the model we will sequences of length 16.

## Put pieces together
To set up everything we can first play with each component on  a toy batch.

The first network is composed as follows:
- A GRU cell
- A linear output layer to generate

---

## TODO

- [ ] fill the cell below with a GRU cell and a Linear layer. It should work !

"""

input_dim = 7
hidden_dim = 10

gru_cell = nn.GRU(input_size=input_dim, hidden_size=hidden_dim, batch_first=True)

output_layer = nn.Linear(hidden_dim, input_dim)

test_batch = Xtrain_reshaped[:1]
out_gru, h_n = gru_cell(test_batch)
predictions = output_layer(out_gru)

print("Input shape:", test_batch.shape)
print("Sortie GRU shape:", out_gru.shape)
print("Predictions shape:", predictions.shape)

"""## Build your own module

Writing your own module is easy in pytorch. It allows you to wrap what you have seen so far. To debug the model, you can first play step-by-step with each layer to ensure you are right with dimensions (it was done earlier). Then, write the class and run the training to evaluate the result (this what we have to do now).

The class inherits from an existing class of pytorch : Module. This means that your class is a Module, but we add some peculiarities. For that purpose you can fill the following code. The two most important parts are the constructor and the forward method.
"""

class GRUPredictor(nn.Module):
    """GRUPredictor is a recurrent model. It takes as input a vector and predict
    the next one given past observations."""
    def __init__(self, input_dim=7, hidden_dim=50, nstack = 1, dropout=0):
        super(GRUPredictor, self).__init__()
        self.idim = input_dim
        self.hdim= hidden_dim
        self.nstack = nstack
        self.dropout=dropout
        self.gru=nn.GRU(input_size=self.idim, hidden_size=self.hdim, num_layers=self.nstack, batch_first=True, dropout=self.dropout if self.nstack > 1 else 0)
        self.out = nn.Linear(self.hdim, self.idim)
    def init_hidden(self, bsz,inputs):
        # This function is given: understand it.
        self.h = th.zeros(self.nstack, bsz, self.hdim,device=inputs.device,dtype=input.dtype)

    def forward(self, x, h0=None):
        if h0 is None:
            bsz=x.shape[0]
            self.init_hidden(bsz,x)
            h0=self.h
            h0=th.zeros(self.nstack,bsz,self.hdim,device=x.device,dtype=x.dtype)
        gru_out, hn = self.gru(x, h0)
        out = self.out(gru_out)
        return out, hn

# A simple test of the model on a mini-batch

"""# A first forecasting model: training and evaluation

Now we have everything. It is time to build a model and to train it:
- select the loss function
- the optimizer can be Adam with a low initial learning (e.g 1e-3 or 5e-4)
- the training algorithm will process mini-batch of e.g 100 sequences (length 16 for each sequence)
- for the validation monitoring, you can use the test set or take the last 10% of sequences
- you can start with a hidden dimension of size 10 and try higher values.


"""

from torch.utils.data import TensorDataset, DataLoader

data = Xtrain_norm
X_train, Y_train = make_sequences(data, 10)
X_train_tensor = th.tensor(X_train, dtype=th.float32)
Y_train_tensor = th.tensor(Y_train, dtype=th.float32)
bsz=100
dataset = TensorDataset(X_train_tensor, Y_train_tensor)
dataloader = DataLoader(dataset, batch_size=bsz, shuffle=True, drop_last=True)


model = GRUPredictor(input_dim=7, hidden_dim=50, nstack=1)
Loss = nn.MSELoss()
learning_rate = 0.001
optimizer = th.optim.Adam(model.parameters(), lr=learning_rate)

num_epochs = 50
losses = []


for epoch in range(num_epochs):
    epoch_loss = 0.0
    model.train()

    for X,Y in dataloader:
        optimizer.zero_grad()
        predictions, _ = model(X)
        loss = Loss(predictions, Y)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()
    avg_loss = epoch_loss / len(dataloader)
    losses.append(avg_loss)

    model.eval()
    with th.no_grad():
        X_test, Y_test = make_sequences(Xtest_norm


# Affichage de la courbe d'apprentissage
plt.figure(figsize=(10, 5))
plt.plot(losses, label='Training Loss', color='blue', linewidth=2)
plt.title('Courbe d\'apprentissage du GRU')
plt.xlabel('Époques')
plt.ylabel('Loss (MSE)')
plt.legend()
plt.grid(True)
plt.show()

"""## Forecasting evaluation
Now you have a trained model, you can use it for forecasting. The first evaluation relies on the same conditions as the training: predict the 7 values for the day after given the true values observed for the current day.

---

## TODO

- [ ] compute the loss on the test set
- [ ] plot the prediction for 100 consecutive days

"""

# TODO

"""## Long term forecasting

We can also evaluate long term predictions: let the model "reads" N=15 true values, and then generate the N following values. For this last generation step the model uses its own predictions as new input.

---

## TODO

- [ ] add a method in the class of your model that can "read" an input sequence and then generate N samples
- [ ] test it with N=15 samples taken from the test data
- [ ] plot the predictions, the truth along with the "one day" predictions for visual comparison
- [ ] to have a better evaluation, we can rescale the values.
"""



"""# Stronger models

---

## TODO
- [ ] try to increase the size of the hidden layer, H=20,50,100.
- [ ] make the full evaluation as before
- [ ] you can also stack recurrent network. Modify the class to allow stacking recurrent layers

"""



"""# Improved training
When you try to predict beyond the next day, the performance clearly drop.

---
## TODO
- [ ] propose and implement another training method.
"""

